name: UPM Release

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 16
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branch: main
          branches: |
            [
              'main'
              'development',
              {
                name: 'preview',
                prerelease: true
              }
            ]
          dry_run: ${{ github.ref == 'refs/heads/development' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}